/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Dhanush
 */
public class intro extends javax.swing.JFrame {
private static final long serialVersionUID = 1L;  
    /**
     * Creates new form intro
     */
    public intro() {
        initComponents();
    }
    public intro(String title) {  
    super(title);  
    // Create dataset  
    DefaultCategoryDataset dataset = createDataset();  
    // Create chart  
    JFreeChart chart = ChartFactory.createLineChart(  
        "Seasonalised vs Deseasonalised data", // Chart title  
        "Year", // X-Axis Label  
        "Data", // Y-Axis Label  
        dataset  
        );  
  
    ChartPanel panel = new ChartPanel(chart);  
    setContentPane(panel);  
  }  
    private DefaultCategoryDataset createDataset() {  
    
    String series1 = "Deeasonalised"; 
    String series2 = "Seasonalised";  
  
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();  
    
    dataset.addValue(2302470, series1, "2012(QTR1)");  
    dataset.addValue(2284638, series1, "2012(QTR2)");  
    dataset.addValue(2045987, series1, "2012(QTR3)");  
    dataset.addValue(2646618, series1, "2012(QTR4)");  
    dataset.addValue(2619270, series1, "2013(QTR1)");  
    dataset.addValue(2595997, series1, "2013(QTR2)");  
    dataset.addValue(2521497, series1, "2013(QTR3)");  
    dataset.addValue(2571932, series1, "2013(QTR4)");   
    dataset.addValue(2665800, series1, "2014(QTR1)");  
    dataset.addValue(2771176, series1, "2014(QTR2)");  
    dataset.addValue(2673156, series1, "2014(QTR3)");  
    dataset.addValue(3172227, series1, "2014(QTR4)");
    dataset.addValue(3110612, series1, "2015(QTR1)");  
    dataset.addValue(2977389, series1, "2015(QTR2)");  
    dataset.addValue(3082128, series1, "2015(QTR3)");  
    dataset.addValue(3352624, series1, "2015(QTR4)");
    dataset.addValue(3330022, series1, "2016(QTR1)");  
    dataset.addValue(3520422, series1, "2016(QTR2)");  
    dataset.addValue(3430376, series1, "2016(QTR3)");  
    dataset.addValue(3344321, series1, "2016(QTR4)"); 
    dataset.addValue(3439073, series1, "2017(QTR1)");  
    dataset.addValue(3455446, series1, "2017(QTR2)");  
    dataset.addValue(3519356, series1, "2017(QTR3)");  
    dataset.addValue(3786207, series1, "2017(QTR4)"); 
    dataset.addValue(3994374, series1, "2018(QTR1)");  
    dataset.addValue(3917574, series1, "2018(QTR2)");  
    dataset.addValue(3693693, series1, "2018(QTR3)");  
    dataset.addValue(3891934, series1, "2018(QTR4)");  
     
    dataset.addValue(2126327.5, series2,"2012(QTR1)");  
    dataset.addValue(2858069.8, series2,"2012(QTR2)");  
    dataset.addValue(1993575.1, series2, "2012(QTR3)");  
    dataset.addValue(2424738.0, series2, "2012(QTR4)");  
    dataset.addValue(2418892.0, series2, "2013(QTR1)");  
    dataset.addValue(3247578.0, series2, "2013(QTR2)");  
    dataset.addValue(2456904.0, series2, "2013(QTR3)");  
    dataset.addValue(2356313.2, series2, "2013(QTR4)");   
    dataset.addValue(2461862.2, series2, "2014(QTR1)");  
    dataset.addValue(3466726.0, series2, "2014(QTR2)");  
    dataset.addValue(2604678.0, series2, "2014(QTR3)");  
    dataset.addValue(2906282.2, series2, "2014(QTR4)");
    dataset.addValue(2872645.2, series2, "2015(QTR1)");  
    dataset.addValue(3724697.5, series2, "2015(QTR2)");  
    dataset.addValue(3003173.2, series2, "2015(QTR3)");  
    dataset.addValue(3071555.8, series2, "2015(QTR4)");
    dataset.addValue(3075270.2, series2, "2016(QTR1)");  
    dataset.addValue(4404028.5, series2, "2016(QTR2)");  
    dataset.addValue(3342500.2, series2, "2016(QTR3)");  
    dataset.addValue(3063948.8, series2, "2016(QTR4)"); 
    dataset.addValue(3175978.8, series2, "2017(QTR1)");  
    dataset.addValue(4322744.0, series2, "2017(QTR2)");  
    dataset.addValue(3429201.0, series2, "2017(QTR3)");  
    dataset.addValue(3468789.2, series2, "2017(QTR4)"); 
    dataset.addValue(3688798.2, series2, "2018(QTR1)");  
    dataset.addValue(4900863.5, series2, "2018(QTR2)");  
    dataset.addValue(3599072.0, series2, "2018(QTR3)");  
    dataset.addValue(3565652.5, series2, "2018(QTR4)");  
  
    return dataset;  
  }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("ANALYSIS ON AIRLINE PASSENGERS");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("SHOW DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("SEASONAL INDEX");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("DESEASONALISED DATA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("TREND VALUES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText("SHOW CHART");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(282, 282, 282))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new showdata().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new seasonal().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

new deseason().setVisible(true);
this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
new trend().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
SwingUtilities.invokeLater(() -> {  
      intro example = new intro("Data Visualisation");  
      example.setAlwaysOnTop(true);  
      example.pack();  
      example.setSize(600, 400);  
      //example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
    });
    }//GEN-LAST:event_jButton5ActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
